# 应用服务器
server:
  tomcat:
    uri-encoding: UTF-8
  port: 30000

spring:
  # 数据源配置
  datasource:
    # 数据库类型(可选值 MySQL、SQLServer、Oracle、DM8、KingbaseES、PostgreSQL，请严格按可选值填写)
    dbtype: MySQL
    dbname: dxqm
    host: 114.116.0.32
    port: 3306
    username: root
    password: root
    # 表空间(当数据库为Oracle、达梦DM8、金仓KingbaseES时表空间必须指定，其他数据库为空即可)
    tablespace:

  devtools:
    restart:
      enabled: true
    freemarker:
      cache: false
  thymeleaf:
    cache: false

  # Redis配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
config:
  # Windows配置（静态资源根目录和代码生成器临时目录）
#  Path: G:\Code\Resources\
#  ServiceDirectoryPath: G:\Code\Resources\TemplateCode\

  # Linux配置（静态资源根目录和代码生成器临时目录）
  Path: /dxqm/Resources/
  ServiceDirectoryPath: /dxqm/Resources/CodeTemp/
  #是否开启测试环境
  TestVersion: true
  # 文件存储类型(local-本地存储，minio-网络存储)
  fileType: minio


jnpf:
  # 使用minio时配置
  minio:
    endpoint: http://114.116.0.32:9000
    accessKey: admin
    secretKey: admin123456
    fileHost: http://114.116.0.32:9000
